version: "3.3"

services:
  client:
    depends_on: 
      - server
    build: ./acs_client
    environment:
      VUE_APP_API_BASE_URL: server:8000/api
    ports:
      - "80:80"
    volumes:
      - ./client:/app


  server:
    build: ./acs_server
    volumes:
      - ./server:/app
    env_file:
    - ./acs_server/prod.env