name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Build and push image for server'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: 'Build and Push Server'
        working-directory: ./acs_server
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/acs_server:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/acs_server:latest
      - name: 'Build and Push Client'
        working-directory: ./acs_client
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/acs_client:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/acs_client:latest 
