name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Build and push image for server'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . --file Dockerfile ${{ secrets.REGISTRY_LOGIN_SERVER }}/acs_server:${{ github.sha }} --tag acs_server:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/acs_server:${{ github.sha }} 

  client-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image for client
        working-directory: ./acs_client
        run: docker build . --file Dockerfile --tag acs_client:$(date +%s)
